### ISSUE TITLE
Level: Conceptualise and develop Tutorial level

### ISSUE THREAD

**Issue by amoshydra** [amoshydra/cs4350-vindicator#83]
_From @amoshydra on September 28, 2017 10:42_

_Copied from original issue: cs4350-foresight/unreal-motion-controller#70_

**Comment by tayjiehao** [comment]
TODO
- [x] Visual aids (i.e. animations) for tutorials
- [ ] Introduce concept of base spell and merge spell

**Comment by amoshydra** [comment]
Progressed in #139 #141 #142
